#!/bin/bash

# Проверяем, был ли передан комментарий
if [ -z "$1" ]; then
  echo "Ошибка: не указан комментарий для коммита."
  echo "Использование: $0 \"Ваш комментарий\""
  if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    # Скрипт запущен напрямую
    exit 1
  else
    # Скрипт вызван через source или .
    return 1
  fi
fi

comment="$1"

# Git-команды
git status
git add .
git status
git commit -m "$comment"
git push
