#!/bin/bash

# Проверяем, был ли передан комментарий
if [ -z "$1" ]; then
  echo "Ошибка: не указан комментарий для коммита."
  echo "Использование: $0 \"Ваш комментарий\""
  if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    exit 1
  else
    return 1
  fi
fi

comment="$1"

# Локальные Git-команды
git status
git add .
git status
git commit -m "$comment"
git push

# Удалённое обновление на сервере
ssh lan-install.online "cd /var/www/www-root/data/www/lan-install.online && GIT_SSH_COMMAND='ssh -i ~/.ssh/git_fursa' git pull"
