#!/bin/bash
set -e

# === Настройки ===
SERVER_PATH="lan-install"
REMOTE_DIR="/var/www/lan-install"
LOGFILE="$HOME/logs/git-deploy.log"

GREEN='\033[32m'
BLUE='\033[34m'
NC='\033[0m' # No Color

info() {
  echo -e "${BLUE}[*] $1${NC}"
}
success() {
  echo -e "${GREEN}[✓] $1${NC}"
}

# === Компиляция на сервере ===
info "Компилируем telegram_notify на сервере..."
ssh "$SERVER_PATH" "gcc -o $REMOTE_DIR/utils/C/notify-bot/telegram_notify $REMOTE_DIR/utils/C/notify-bot/telegram_notify.c -lcurl"

info "Компилируем sys-monitor на сервере..."
ssh "$SERVER_PATH" "gcc -o $REMOTE_DIR/utils/C/sys-monitor/sys-monitor $REMOTE_DIR/utils/C/sys-monitor/sys-monitor.c"

if [ $? -eq 0 ]; then
  success "Утилиты успешно скомпилированы и обновлены!"
else
  echo "Ошибка компиляции."
  exit 1
fi
